apiVersion: v1
kind: Secret
metadata:
  name: stacklayer-mysql-secret
  labels:
    app: stacklayer-wordpress
type: Opaque
stringData:
  # Replace with your actual MySQL server FQDN:
  WORDPRESS_DB_HOST: "stacklayer-mysql-UNIQUE_SUFFIX.mysql.database.azure.com"
  WORDPRESS_DB_NAME: "stacklayer_wordpressdb"
  WORDPRESS_DB_USER: "stackadmin"
  WORDPRESS_DB_PASSWORD: "StackLayer2026!Secure"
