apiVersion: v1
kind: Secret
metadata:
  name: stacklayer-mysql-secret
  labels:
    app: stacklayer-phpmyadmin
type: Opaque
stringData:
  PMA_HOST: "<YOUR_MYSQL_SERVER_NAME>.mysql.database.azure.com"
  PMA_USER: "stacklayeradmin"
  PMA_PASSWORD: "VaultPassword@2026!Azure"
