apiVersion: v1
kind: Service
metadata:
  name: stacklayer-phpmyadmin-service
  labels:
    app: stacklayer-phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: stacklayer-phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
