apiVersion: v1
kind: Secret
metadata:
  name: stacklayer-app-secret
  labels:
    app: stacklayer-secure-app
type: Opaque
stringData:
  DB_USERNAME: "stacklayer_admin"
  DB_PASSWORD: "VaultPassword@2026!Azure"
  API_AUTH_TOKEN: "sec_live_948271039472619"
